# Cargo CI workflow to build and test

name: Cargo CI Build & Test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
      - uses: glslang/setup-masm@v1
      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Cargo fmt
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check
      - name: Cargo update
        run: cargo update
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
